name: Auto Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Tag and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        go-version: [ 1.24.x ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Get Latest Tag
        id: get_tag
        run: |
          git fetch --tags
          latest_tag=$(git tag --sort=-version:refname | head -n 1)
          echo "latest=$latest_tag" >> $GITHUB_OUTPUT

      - name: Calculate Next Tag
        id: tagger
        run: |
          latest=${{ steps.get_tag.outputs.latest }}
          if [[ "$latest" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
            major=${BASH_REMATCH[1]}
            minor=${BASH_REMATCH[2]}
            patch=${BASH_REMATCH[3]}
            new_tag="v$major.$minor.$((patch+1))"
          else
            new_tag="v0.1.0"
          fi
          echo "next=$new_tag" >> $GITHUB_OUTPUT

      - name: Create Git Tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ steps.tagger.outputs.next }}
          git push origin ${{ steps.tagger.outputs.next }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tagger.outputs.next }}
